version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geocoder-db
    restart: always
    environment:
      POSTGRES_USER: geocoder
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: geocoder
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
